[package]
name = "chibicc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.0"
spin = "0.5.2"

[[bin]]
name = "chibicc"
path = "src/cli/main.rs"